server:
  port: 8080

spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_DELAY=-1;MODE=MySQL
    initialize: true
    username: sa # database 用戶名
    password:  # database 密碼    

  sql:
    init:
      encoding: UTF-8
      mode|: always      
      
  jpa:
    show-sql: true  
    defer-datasource-initialization: true

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER      
      
      
logging:
    name: C:/Users/User/Documents/SpringWorkSpace/OAuth2Server/logsauth.log
        
management:
  endpoint:
    shutdown:
      enabled: true           
    
# 自定义jwt key
jwt:
  tokenHeader: Authorization #JWT存储的request header
  secret: 1048c08c3a502d78feex2b59ce243342 #JWT加密解密使用的密鑰
  expiration: 604800 #JWT的使用期限(60*60*24)
  tokenHead: Bearer  #JWT负载中token前置字串      
    
    
springfox:
  documentation:
    enabled: true